/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSeriesSlugRouteImport } from './routes/series.$seriesSlug'
import { Route as CoversBookIdRouteImport } from './routes/covers.$bookId'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as AuthorsAuthorSlugRouteImport } from './routes/authors.$authorSlug'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ApiRescanRouteImport } from './routes/api.rescan'
import { Route as ApiRequestBookRouteImport } from './routes/api.request-book'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as DownloadBookIdFormatRouteImport } from './routes/download.$bookId.$format'
import { Route as ApiRequestBookReleasesRouteImport } from './routes/api.request-book.releases'
import { Route as ApiAuthPlexRouteImport } from './routes/api.auth.plex'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesSlugRoute = SeriesSeriesSlugRouteImport.update({
  id: '/series/$seriesSlug',
  path: '/series/$seriesSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoversBookIdRoute = CoversBookIdRouteImport.update({
  id: '/covers/$bookId',
  path: '/covers/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorSlugRoute = AuthorsAuthorSlugRouteImport.update({
  id: '/authors/$authorSlug',
  path: '/authors/$authorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRescanRoute = ApiRescanRouteImport.update({
  id: '/api/rescan',
  path: '/api/rescan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestBookRoute = ApiRequestBookRouteImport.update({
  id: '/api/request-book',
  path: '/api/request-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadBookIdFormatRoute = DownloadBookIdFormatRouteImport.update({
  id: '/download/$bookId/$format',
  path: '/download/$bookId/$format',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestBookReleasesRoute = ApiRequestBookReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => ApiRequestBookRoute,
} as any)
const ApiAuthPlexRoute = ApiAuthPlexRouteImport.update({
  id: '/api/auth/plex',
  path: '/api/auth/plex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/request-book': typeof ApiRequestBookRouteWithChildren
  '/api/rescan': typeof ApiRescanRoute
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/covers/$bookId': typeof CoversBookIdRoute
  '/series/$seriesSlug': typeof SeriesSeriesSlugRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/plex': typeof ApiAuthPlexRoute
  '/api/request-book/releases': typeof ApiRequestBookReleasesRoute
  '/download/$bookId/$format': typeof DownloadBookIdFormatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/request-book': typeof ApiRequestBookRouteWithChildren
  '/api/rescan': typeof ApiRescanRoute
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/covers/$bookId': typeof CoversBookIdRoute
  '/series/$seriesSlug': typeof SeriesSeriesSlugRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/plex': typeof ApiAuthPlexRoute
  '/api/request-book/releases': typeof ApiRequestBookReleasesRoute
  '/download/$bookId/$format': typeof DownloadBookIdFormatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/request-book': typeof ApiRequestBookRouteWithChildren
  '/api/rescan': typeof ApiRescanRoute
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/covers/$bookId': typeof CoversBookIdRoute
  '/series/$seriesSlug': typeof SeriesSeriesSlugRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/plex': typeof ApiAuthPlexRoute
  '/api/request-book/releases': typeof ApiRequestBookReleasesRoute
  '/download/$bookId/$format': typeof DownloadBookIdFormatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/health'
    | '/api/request-book'
    | '/api/rescan'
    | '/api/search'
    | '/authors/$authorSlug'
    | '/books/$bookId'
    | '/covers/$bookId'
    | '/series/$seriesSlug'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/plex'
    | '/api/request-book/releases'
    | '/download/$bookId/$format'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/api/request-book'
    | '/api/rescan'
    | '/api/search'
    | '/authors/$authorSlug'
    | '/books/$bookId'
    | '/covers/$bookId'
    | '/series/$seriesSlug'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/plex'
    | '/api/request-book/releases'
    | '/download/$bookId/$format'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/health'
    | '/api/request-book'
    | '/api/rescan'
    | '/api/search'
    | '/authors/$authorSlug'
    | '/books/$bookId'
    | '/covers/$bookId'
    | '/series/$seriesSlug'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/plex'
    | '/api/request-book/releases'
    | '/download/$bookId/$format'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRequestBookRoute: typeof ApiRequestBookRouteWithChildren
  ApiRescanRoute: typeof ApiRescanRoute
  ApiSearchRoute: typeof ApiSearchRoute
  AuthorsAuthorSlugRoute: typeof AuthorsAuthorSlugRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  CoversBookIdRoute: typeof CoversBookIdRoute
  SeriesSeriesSlugRoute: typeof SeriesSeriesSlugRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthPlexRoute: typeof ApiAuthPlexRoute
  DownloadBookIdFormatRoute: typeof DownloadBookIdFormatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesSlug': {
      id: '/series/$seriesSlug'
      path: '/series/$seriesSlug'
      fullPath: '/series/$seriesSlug'
      preLoaderRoute: typeof SeriesSeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covers/$bookId': {
      id: '/covers/$bookId'
      path: '/covers/$bookId'
      fullPath: '/covers/$bookId'
      preLoaderRoute: typeof CoversBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorSlug': {
      id: '/authors/$authorSlug'
      path: '/authors/$authorSlug'
      fullPath: '/authors/$authorSlug'
      preLoaderRoute: typeof AuthorsAuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rescan': {
      id: '/api/rescan'
      path: '/api/rescan'
      fullPath: '/api/rescan'
      preLoaderRoute: typeof ApiRescanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-book': {
      id: '/api/request-book'
      path: '/api/request-book'
      fullPath: '/api/request-book'
      preLoaderRoute: typeof ApiRequestBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$bookId/$format': {
      id: '/download/$bookId/$format'
      path: '/download/$bookId/$format'
      fullPath: '/download/$bookId/$format'
      preLoaderRoute: typeof DownloadBookIdFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-book/releases': {
      id: '/api/request-book/releases'
      path: '/releases'
      fullPath: '/api/request-book/releases'
      preLoaderRoute: typeof ApiRequestBookReleasesRouteImport
      parentRoute: typeof ApiRequestBookRoute
    }
    '/api/auth/plex': {
      id: '/api/auth/plex'
      path: '/api/auth/plex'
      fullPath: '/api/auth/plex'
      preLoaderRoute: typeof ApiAuthPlexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiRequestBookRouteChildren {
  ApiRequestBookReleasesRoute: typeof ApiRequestBookReleasesRoute
}

const ApiRequestBookRouteChildren: ApiRequestBookRouteChildren = {
  ApiRequestBookReleasesRoute: ApiRequestBookReleasesRoute,
}

const ApiRequestBookRouteWithChildren = ApiRequestBookRoute._addFileChildren(
  ApiRequestBookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRequestBookRoute: ApiRequestBookRouteWithChildren,
  ApiRescanRoute: ApiRescanRoute,
  ApiSearchRoute: ApiSearchRoute,
  AuthorsAuthorSlugRoute: AuthorsAuthorSlugRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  CoversBookIdRoute: CoversBookIdRoute,
  SeriesSeriesSlugRoute: SeriesSeriesSlugRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthPlexRoute: ApiAuthPlexRoute,
  DownloadBookIdFormatRoute: DownloadBookIdFormatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
