/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSeriesSlugRouteImport } from './routes/series.$seriesSlug'
import { Route as CoversBookIdRouteImport } from './routes/covers.$bookId'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as AuthorsAuthorSlugRouteImport } from './routes/authors.$authorSlug'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ApiRescanRouteImport } from './routes/api.rescan'
import { Route as ApiRequestBookRouteImport } from './routes/api.request-book'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as DownloadBookIdFormatRouteImport } from './routes/download.$bookId.$format'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesSlugRoute = SeriesSeriesSlugRouteImport.update({
  id: '/series/$seriesSlug',
  path: '/series/$seriesSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoversBookIdRoute = CoversBookIdRouteImport.update({
  id: '/covers/$bookId',
  path: '/covers/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorSlugRoute = AuthorsAuthorSlugRouteImport.update({
  id: '/authors/$authorSlug',
  path: '/authors/$authorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRescanRoute = ApiRescanRouteImport.update({
  id: '/api/rescan',
  path: '/api/rescan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestBookRoute = ApiRequestBookRouteImport.update({
  id: '/api/request-book',
  path: '/api/request-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadBookIdFormatRoute = DownloadBookIdFormatRouteImport.update({
  id: '/download/$bookId/$format',
  path: '/download/$bookId/$format',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/request-book': typeof ApiRequestBookRoute
  '/api/rescan': typeof ApiRescanRoute
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/covers/$bookId': typeof CoversBookIdRoute
  '/series/$seriesSlug': typeof SeriesSeriesSlugRoute
  '/download/$bookId/$format': typeof DownloadBookIdFormatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/request-book': typeof ApiRequestBookRoute
  '/api/rescan': typeof ApiRescanRoute
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/covers/$bookId': typeof CoversBookIdRoute
  '/series/$seriesSlug': typeof SeriesSeriesSlugRoute
  '/download/$bookId/$format': typeof DownloadBookIdFormatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/request-book': typeof ApiRequestBookRoute
  '/api/rescan': typeof ApiRescanRoute
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/covers/$bookId': typeof CoversBookIdRoute
  '/series/$seriesSlug': typeof SeriesSeriesSlugRoute
  '/download/$bookId/$format': typeof DownloadBookIdFormatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/request-book'
    | '/api/rescan'
    | '/api/search'
    | '/authors/$authorSlug'
    | '/books/$bookId'
    | '/covers/$bookId'
    | '/series/$seriesSlug'
    | '/download/$bookId/$format'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/request-book'
    | '/api/rescan'
    | '/api/search'
    | '/authors/$authorSlug'
    | '/books/$bookId'
    | '/covers/$bookId'
    | '/series/$seriesSlug'
    | '/download/$bookId/$format'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/request-book'
    | '/api/rescan'
    | '/api/search'
    | '/authors/$authorSlug'
    | '/books/$bookId'
    | '/covers/$bookId'
    | '/series/$seriesSlug'
    | '/download/$bookId/$format'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRequestBookRoute: typeof ApiRequestBookRoute
  ApiRescanRoute: typeof ApiRescanRoute
  ApiSearchRoute: typeof ApiSearchRoute
  AuthorsAuthorSlugRoute: typeof AuthorsAuthorSlugRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  CoversBookIdRoute: typeof CoversBookIdRoute
  SeriesSeriesSlugRoute: typeof SeriesSeriesSlugRoute
  DownloadBookIdFormatRoute: typeof DownloadBookIdFormatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesSlug': {
      id: '/series/$seriesSlug'
      path: '/series/$seriesSlug'
      fullPath: '/series/$seriesSlug'
      preLoaderRoute: typeof SeriesSeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covers/$bookId': {
      id: '/covers/$bookId'
      path: '/covers/$bookId'
      fullPath: '/covers/$bookId'
      preLoaderRoute: typeof CoversBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorSlug': {
      id: '/authors/$authorSlug'
      path: '/authors/$authorSlug'
      fullPath: '/authors/$authorSlug'
      preLoaderRoute: typeof AuthorsAuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rescan': {
      id: '/api/rescan'
      path: '/api/rescan'
      fullPath: '/api/rescan'
      preLoaderRoute: typeof ApiRescanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-book': {
      id: '/api/request-book'
      path: '/api/request-book'
      fullPath: '/api/request-book'
      preLoaderRoute: typeof ApiRequestBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$bookId/$format': {
      id: '/download/$bookId/$format'
      path: '/download/$bookId/$format'
      fullPath: '/download/$bookId/$format'
      preLoaderRoute: typeof DownloadBookIdFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRequestBookRoute: ApiRequestBookRoute,
  ApiRescanRoute: ApiRescanRoute,
  ApiSearchRoute: ApiSearchRoute,
  AuthorsAuthorSlugRoute: AuthorsAuthorSlugRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  CoversBookIdRoute: CoversBookIdRoute,
  SeriesSeriesSlugRoute: SeriesSeriesSlugRoute,
  DownloadBookIdFormatRoute: DownloadBookIdFormatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
